name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
      shell: bash

    - name: Install Dependencies with vcpkg
      run: |
        ./vcpkg/vcpkg install --feature-flags=manifests && ./vcpkg/vcpkg integrate install
      shell: bash

    - name: Configure CMake
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=D:/a/dlssg-to-fsr3/dlssg-to-fsr3/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: ./Make-Release.ps1

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: build/Release