name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: ./Make-Release.ps1

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: build/Release